UPDATE crm_accounts SET address='4949 Celebration Pointe Ave', city='Gainesville', state='FL' WHERE id=529;
UPDATE crm_accounts SET address='204 NE Hwy 441', city='Micanopy', state='FL' WHERE id=549;
UPDATE crm_accounts SET address='2019 E Silver Springs Blvd', city='Ocala', state='FL' WHERE id=683;
UPDATE crm_accounts SET address='2331 NW 13th St', city='Gainesville', state='FL' WHERE id=512;
UPDATE crm_accounts SET address='1201 SW 16TH AVE', city='Gainesville', state='FL' WHERE id=393;
UPDATE crm_accounts SET address='1017 WEST UNIVERSITY AVENUE', city='Gainesville', state='FL' WHERE id=919;
UPDATE crm_accounts SET address='3842 W Newberry Rd', city='Gainesville', state='FL' WHERE id=466;
UPDATE crm_accounts SET address='2751 W Torch Lake Dr', city='The Villages', state='FL' WHERE id=339;
UPDATE crm_accounts SET address='30 N Main St', city='Gainesville', state='FL' WHERE id=513;
UPDATE crm_accounts SET address='25335 WEST NEWBERRY RD', city='Newberry', state='FL' WHERE id=500;
UPDATE crm_accounts SET address='1545 NW 26th Ave', city='Chiefland', state='FL' WHERE id=503;
UPDATE crm_accounts SET address='11400 Turkey Creek Blvd', city='Alachua', state='FL' WHERE id=499;
UPDATE crm_accounts SET address='2 W Fort King St', city='Ocala', state='FL' WHERE id=1062;
UPDATE crm_accounts SET address='6111 SW 89 Ct Rd', city='Ocala', state='FL' WHERE id=485;
UPDATE crm_accounts SET address='5180 & 5186 SW 34TH STREET', city='Gainesville', state='FL' WHERE id=514;
UPDATE crm_accounts SET address='766 MARILEE PLACE', city='The Villages', state='FL' WHERE id=501;
UPDATE crm_accounts SET address='3445 W University Ave', city='Gainesville', state='FL' WHERE id=515;
UPDATE crm_accounts SET address='4860 NW 39TH AVENUE', city='Gainesville', state='FL' WHERE id=505;
UPDATE crm_accounts SET address='6998 US-27 Suite 112', city='Ocala', state='FL' WHERE id=480;
UPDATE crm_accounts SET address='2440 SW 76th St Suite 110', city='Gainesville', state='FL' WHERE id=484;
UPDATE crm_accounts SET address='48 S Magnolia Ave', city='Ocala', state='FL' WHERE id=507;
UPDATE crm_accounts SET address='103 SE 1st Ave', city='Ocala', state='FL' WHERE id=475;
UPDATE crm_accounts SET address='232 SE 1st St', city='Gainesville', state='FL' WHERE id=523;
UPDATE crm_accounts SET address='2405 W 27th Ave', city='Ocala', state='FL' WHERE id=491;
UPDATE crm_accounts SET address='1800 NE 23rd Ave', city='Gainesville', state='FL' WHERE id=528;
UPDATE crm_accounts SET address='1000 Old Mill Run', city='The Villages', state='FL' WHERE id=510;
UPDATE crm_accounts SET address='3965 Plaza Blvd Ste 10', city='Gainesville', state='FL' WHERE id=477;
UPDATE crm_accounts SET address='2000 Crawfordville Hwy STE G', city='Crawfordville', state='FL' WHERE id=187;
UPDATE crm_accounts SET address='2810 SHARER RD. UNIT#11', city='Tallahassee', state='FL' WHERE id=199;
UPDATE crm_accounts SET address='100 Tyron Cir', city='Tallahassee', state='FL' WHERE id=158;
UPDATE crm_accounts SET address='81001 S Gadsden St', city='Tallahassee', state='FL' WHERE id=105;
UPDATE crm_accounts SET address='3421 BANNERMAN RD', city='Tallahassee', state='FL' WHERE id=157;
UPDATE crm_accounts SET address='201 E Park Ave', city='Tallahassee', state='FL' WHERE id=102;
UPDATE crm_accounts SET address='3596 KINDHEGA DR.', city='Tallahassee', state='FL' WHERE id=145;
UPDATE crm_accounts SET address='620-1 Railroad Sq', city='Tallahassee', state='FL' WHERE id=162;
UPDATE crm_accounts SET address='1458 S MONROE STREET', city='Tallahassee', state='FL' WHERE id=241;
UPDATE crm_accounts SET address='1123 Thomasville Rd', city='Tallahassee', state='FL' WHERE id=250;
UPDATE crm_accounts SET address='805 S MACOMB ST', city='TALLAHASSEE', state='FL' WHERE id=214;
UPDATE crm_accounts SET address='600 W Gaines St', city='Tallahassee', state='FL' WHERE id=1121;
UPDATE crm_accounts SET address='3305 CAPITAL CIR NE', city='Tallahassee', state='FL' WHERE id=150;
UPDATE crm_accounts SET address='2910 Kerry Forest Pkwy', city='Tallahassee', state='FL' WHERE id=121;
UPDATE crm_accounts SET address='3491 Thomasville Rd', city='Tallahassee', state='FL' WHERE id=64;
UPDATE crm_accounts SET address='6668 Thomasville Rd', city='Tallahassee', state='FL' WHERE id=39;
UPDATE crm_accounts SET address='3551 BLAIRSTONE RD', city='Tallahassee', state='FL' WHERE id=62;
UPDATE crm_accounts SET address='2662 Fleischmann Rd', city='Tallahassee', state='FL' WHERE id=54;
UPDATE crm_accounts SET address='603 W Gaines St', city='Tallahassee', state='FL' WHERE id=119;
UPDATE crm_accounts SET address='1105 THARPE STREET', city='TALLAHASSEE', state='FL' WHERE id=210;
UPDATE crm_accounts SET address='202 S Adams St', city='Tallahassee', state='FL' WHERE id=154;
UPDATE crm_accounts SET address='2475 Apalachee Pkwy', city='Tallahassee', state='FL' WHERE id=125;
UPDATE crm_accounts SET address='513 W Gaines St', city='Tallahassee', state='FL' WHERE id=34;
