UPDATE crm_accounts SET address='6830 Suwannee Plaza Ln', city='Live Oak', state='FL' WHERE id=1175;
UPDATE crm_accounts SET address='563 FL-47', city='Lake City', state='FL' WHERE id=1177;
UPDATE crm_accounts SET address='313 NW Commons Loop', city='Lake City', state='FL' WHERE id=467;
UPDATE crm_accounts SET address='296 ROYAL PALMS DRIVE', city='Atlantic Beach', state='FL' WHERE id=1012;
UPDATE crm_accounts SET address='15 St George Street', city='Saint Augustine', state='FL' WHERE id=1003;
UPDATE crm_accounts SET address='1521 MARGARET ST', city='Jacksonville', state='FL' WHERE id=989;
UPDATE crm_accounts SET address='35 San Marco Ave', city='St. Augustine', state='FL' WHERE id=966;
UPDATE crm_accounts SET address='2461 3RD ST SOUTH', city='Jacksonville Beach', state='FL' WHERE id=993;
UPDATE crm_accounts SET address='1261 King St', city='Jacksonville', state='FL' WHERE id=260;
UPDATE crm_accounts SET address='24 CATHEDRAL PLACE', city='Saint Augustine', state='FL' WHERE id=1007;
UPDATE crm_accounts SET address='9825 San Jose Blvd', city='Jacksonville', state='FL' WHERE id=996;
UPDATE crm_accounts SET address='1011 ATLANTIC BLVD UNIT #6', city='Atlantic Beach', state='FL' WHERE id=1002;
UPDATE crm_accounts SET address='1975 SILVERLEAF PKWY', city='Saint Augustine', state='FL' WHERE id=492;
UPDATE crm_accounts SET address='474305 State Rd 200', city='Fernandina Beach', state='FL' WHERE id=1006;
UPDATE crm_accounts SET address='1 Anastasia Blvd', city='St. Augustine', state='FL' WHERE id=546;
UPDATE crm_accounts SET address='1605 County Road 220', city='Fleming Island', state='FL' WHERE id=1020;
UPDATE crm_accounts SET address='1037 Park St', city='Jacksonville', state='FL' WHERE id=420;
UPDATE crm_accounts SET address='450 State Road 13', city='Fruit Cove', state='FL' WHERE id=984;
UPDATE crm_accounts SET address='14376 Beach Blvd', city='Jacksonville', state='FL' WHERE id=949;
UPDATE crm_accounts SET address='929 Edgewood Ave S.', city='Jacksonville', state='FL' WHERE id=979;
UPDATE crm_accounts SET address='10601 San Jose Blvd', city='Jacksonville', state='FL' WHERE id=14;
UPDATE crm_accounts SET address='295 Pine Lakes Drive', city='Ponte Vedra', state='FL' WHERE id=970;
UPDATE crm_accounts SET address='1585 3RD STREET NORTH', city='Jacksonville Beach', state='FL' WHERE id=975;
UPDATE crm_accounts SET address='1124 NORTH 3RD ST', city='Jacksonville Beach', state='FL' WHERE id=987;
UPDATE crm_accounts SET address='13275 City Square Dr', city='Jacksonville', state='FL' WHERE id=998;
UPDATE crm_accounts SET address='6 Aviles St', city='St. Augustine', state='FL' WHERE id=968;
UPDATE crm_accounts SET address='61 San Marco Ave', city='St. Augustine', state='FL' WHERE id=971;
UPDATE crm_accounts SET address='1034 Edgewood Ave S', city='Jacksonville', state='FL' WHERE id=1013;
UPDATE crm_accounts SET address='119 E Bay St', city='Jacksonville', state='FL' WHERE id=826;
UPDATE crm_accounts SET address='1034 Park St', city='Jacksonville', state='FL' WHERE id=988;
UPDATE crm_accounts SET address='61 N LAURA STREET', city='Jacksonville', state='FL' WHERE id=999;
UPDATE crm_accounts SET address='4070 HERSCHEL STREET', city='Jacksonville', state='FL' WHERE id=781;
UPDATE crm_accounts SET address='245 Nocatee Center Way', city='Ponte Vedra Beach', state='FL' WHERE id=1000;
UPDATE crm_accounts SET address='12601 San Jose Blvd', city='Jacksonville', state='FL' WHERE id=554;
UPDATE crm_accounts SET address='715 RIVERSIDE AVENUE', city='JACKSONVILLE', state='FL' WHERE id=980;
UPDATE crm_accounts SET address='11112 San Jose Blvd', city='Jacksonville', state='FL' WHERE id=259;
UPDATE crm_accounts SET address='840 A1A N', city='Ponte Vedra Beach', state='FL' WHERE id=278;
UPDATE crm_accounts SET address='4413 Town Center Pkwy Ste 300', city='Jacksonville', state='FL' WHERE id=956;
UPDATE crm_accounts SET address='4180 3rd St S', city='Jacksonville Beach', state='FL' WHERE id=953;
UPDATE crm_accounts SET address='1302 Harrison Ave', city='Panama City', state='FL' WHERE id=876;
UPDATE crm_accounts SET address='1519 Tennessee Ave', city='Lynn Haven', state='FL' WHERE id=856;
UPDATE crm_accounts SET address='1125 Beck Ave', city='Panama City', state='FL' WHERE id=855;
UPDATE crm_accounts SET address='601 S PIER PARK DR', city='Panama City Beach', state='FL' WHERE id=1053;
UPDATE crm_accounts SET address='212 Monument Avenue', city='Port St Joe', state='FL' WHERE id=879;
UPDATE crm_accounts SET address='8501 Thomas Dr', city='Panama City Beach', state='FL' WHERE id=878;
UPDATE crm_accounts SET address='4368 W County Hwy 30A', city='Santa Rosa Beach', state='FL' WHERE id=838;
UPDATE crm_accounts SET address='11226 Hutchison Blvd', city='Panama City Beach', state='FL' WHERE id=453;
UPDATE crm_accounts SET address='27 BAY MAGNOLIA LANE', city='Santa Rosa Beach', state='FL' WHERE id=383;
UPDATE crm_accounts SET address='34 Goldenrod Cir', city='Santa Rosa Beach', state='FL' WHERE id=845;
UPDATE crm_accounts SET address='1127 1/2 Beck Ave', city='Panama City', state='FL' WHERE id=862;
