UPDATE crm_accounts SET address='6800 THOMASVILLE RD.', city='TALLAHASSEE', state='FL' WHERE id=61;
UPDATE crm_accounts SET address='1650 N Monroe St', city='Tallahassee', state='FL' WHERE id=208;
UPDATE crm_accounts SET address='1950 Thomasville Rd', city='Tallahassee', state='FL' WHERE id=85;
UPDATE crm_accounts SET address='80 N Jefferson St', city='Monticello', state='FL' WHERE id=57;
UPDATE crm_accounts SET address='2020 W Pensacola St', city='Tallahassee', state='FL' WHERE id=245;
UPDATE crm_accounts SET address='3390 Capital Cir NE', city='Tallahassee', state='FL' WHERE id=49;
UPDATE crm_accounts SET address='151 LAUGHLING GULL LAND', city='Carrabelle', state='FL' WHERE id=129;
UPDATE crm_accounts SET address='320 E Tennessee St', city='Tallahassee', state='FL' WHERE id=104;
UPDATE crm_accounts SET address='3700 Golden Eagle Dr E', city='Tallahassee', state='FL' WHERE id=43;
UPDATE crm_accounts SET address='2738 Capital Cir NE', city='Tallahassee', state='FL' WHERE id=37;
UPDATE crm_accounts SET address='1026 N Monroe St', city='Tallahassee', state='FL' WHERE id=135;
UPDATE crm_accounts SET address='2837 Coastal Hwy', city='Crawfordville', state='FL' WHERE id=91;
UPDATE crm_accounts SET address='1954 Village Green Way', city='Tallahassee', state='FL' WHERE id=93;
UPDATE crm_accounts SET address='1304 N Monroe', city='Tallahassee', state='FL' WHERE id=110;
UPDATE crm_accounts SET address='6668-9 THOMASVILLE RD', city='Tallahassee', state='FL' WHERE id=246;
UPDATE crm_accounts SET address='306 1st St NW', city='Havana', state='FL' WHERE id=112;
UPDATE crm_accounts SET address='1307 N MONROE ST', city='Tallahassee', state='FL' WHERE id=165;
UPDATE crm_accounts SET address='4620 WOODVILLE HWY', city='Tallahassee', state='FL' WHERE id=147;
UPDATE crm_accounts SET address='3626 MAHAN DR.', city='Tallahassee', state='FL' WHERE id=160;
UPDATE crm_accounts SET address='3129 COOKS LANDING RD.', city='Quincy', state='FL' WHERE id=144;
UPDATE crm_accounts SET address='3862 Coastal Hwy', city='Crawfordville', state='FL' WHERE id=167;
UPDATE crm_accounts SET address='6653 THOMASVILLE RD', city='Tallahassee', state='FL' WHERE id=134;
UPDATE crm_accounts SET address='2700 Centerville Rd', city='Tallahassee', state='FL' WHERE id=183;
UPDATE crm_accounts SET address='1505 Jackson Bluff Rd', city='Tallahassee', state='FL' WHERE id=189;
UPDATE crm_accounts SET address='1840 N. MONROE STREET', city='TALLAHASSEE', state='FL' WHERE id=240;
UPDATE crm_accounts SET address='205 EAST PARK AVENUE SUITE#2', city='Tallahassee', state='FL' WHERE id=94;
UPDATE crm_accounts SET address='1481 Timberlane Rd', city='Tallahassee', state='FL' WHERE id=231;
UPDATE crm_accounts SET address='1242 S. JEFFERSON ST', city='Monticello', state='FL' WHERE id=226;
UPDATE crm_accounts SET address='200 COCA COLA AVE.', city='Havana', state='FL' WHERE id=216;
UPDATE crm_accounts SET address='445 SW COUNTRY CLUB RD', city='Madison', state='FL' WHERE id=232;
UPDATE crm_accounts SET address='325 N Bronough St', city='Tallahassee', state='FL' WHERE id=21;
UPDATE crm_accounts SET address='1011 S. MAGNOLIA', city='Tallahassee', state='FL' WHERE id=152;
UPDATE crm_accounts SET address='Hwy 98', city='Carrabelle', state='FL' WHERE id=83;
UPDATE crm_accounts SET address='14 Coastal Hwy', city='Panacea', state='FL' WHERE id=251;
UPDATE crm_accounts SET address='415 N Monroe St', city='Tallahassee', state='FL' WHERE id=46;
UPDATE crm_accounts SET address='7505 Preservation Rd', city='Tallahassee', state='FL' WHERE id=65;
UPDATE crm_accounts SET address='415 SAINT FRANCIS ST', city='Tallahassee', state='FL' WHERE id=109;
UPDATE crm_accounts SET address='1925 N MONROE ST', city='Tallahassee', state='FL' WHERE id=60;
UPDATE crm_accounts SET address='411 N MAGNOLIA DRIVE', city='Tallahassee', state='FL' WHERE id=239;
UPDATE crm_accounts SET address='3031 Crump rd', city='Tallahassee', state='FL' WHERE id=211;
UPDATE crm_accounts SET address='1018 Apalachee Pkwy', city='Tallahassee', state='FL' WHERE id=138;
UPDATE crm_accounts SET address='1318 N. MONROE SUITE B', city='Tallahassee', state='FL' WHERE id=163;
UPDATE crm_accounts SET address='1123 Thomasville Rd', city='Tallahassee', state='FL' WHERE id=200;
UPDATE crm_accounts SET address='8147 APALACHEE PARKWAY', city='Tallahassee', state='FL' WHERE id=139;
UPDATE crm_accounts SET address='1460 Market St', city='Tallahassee', state='FL' WHERE id=68;
UPDATE crm_accounts SET address='1327 S Monroe Unit 105', city='Tallahassee', state='FL' WHERE id=66;
UPDATE crm_accounts SET address='1123 THOMASVILLE RD', city='TALLAHASSEE', state='FL' WHERE id=141;
UPDATE crm_accounts SET address='101 W Pine Ave', city='St George Island', state='FL' WHERE id=126;
UPDATE crm_accounts SET address='400 Cedar Hill Rd', city='Tallahassee', state='FL' WHERE id=175;
UPDATE crm_accounts SET address='3813 N. MONROE ST', city='Tallahassee', state='FL' WHERE id=58;
