UPDATE crm_accounts SET address='1216 - 4 NORTH MONROE STREET', city='Tallahassee', state='FL' WHERE id=159;
UPDATE crm_accounts SET address='504 All Saints St', city='Tallahassee', state='FL' WHERE id=197;
UPDATE crm_accounts SET address='850 PORT LEON DRIVE', city='St. Marks', state='FL' WHERE id=55;
UPDATE crm_accounts SET address='302 W 9TH AVE', city='Havana', state='FL' WHERE id=133;
UPDATE crm_accounts SET address='2111 NE CAPITAL CIRCLE', city='Tallahassee', state='FL' WHERE id=146;
UPDATE crm_accounts SET address='1235 APALACHEE PARKWAY', city='Tallahassee', state='FL' WHERE id=40;
UPDATE crm_accounts SET address='316 WEST TENNESSEE STREET', city='Tallahassee', state='FL' WHERE id=171;
UPDATE crm_accounts SET address='3870 COASTAL HWY', city='Crawfordville', state='FL' WHERE id=191;
UPDATE crm_accounts SET address='1105 E Lafayette St', city='Tallahassee', state='FL' WHERE id=594;
UPDATE crm_accounts SET address='228 FRANKLIN BLVD', city='St. George Island', state='FL' WHERE id=87;
UPDATE crm_accounts SET address='1600 Summit Lake Dr', city='Tallahassee', state='FL' WHERE id=209;
UPDATE crm_accounts SET address='10 N Adams St', city='Quincy', state='FL' WHERE id=173;
UPDATE crm_accounts SET address='123 East 5th Ave', city='Tallahassee', state='FL' WHERE id=108;
UPDATE crm_accounts SET address='2550 Pottsdamer St', city='Tallahassee', state='FL' WHERE id=156;
UPDATE crm_accounts SET address='101 S Adams St', city='Tallahassee', state='FL' WHERE id=107;
UPDATE crm_accounts SET address='2717 Mahan Dr', city='Tallahassee', state='FL' WHERE id=31;
UPDATE crm_accounts SET address='2911 THOMASVILLE ROAD', city='Tallahassee', state='FL' WHERE id=67;
UPDATE crm_accounts SET address='101 NORTH BLAIRSTONE RD', city='Tallahassee', state='FL' WHERE id=555;
UPDATE crm_accounts SET address='824 RAILROAD AVE', city='Tallahassee', state='FL' WHERE id=573;
UPDATE crm_accounts SET address='3431 BANNERMAN RD', city='Tallahassee', state='FL' WHERE id=166;
UPDATE crm_accounts SET address='1700-9 NORTH MONROE ST', city='Tallahassee', state='FL' WHERE id=176;
UPDATE crm_accounts SET address='6725 Mahan Dr', city='Tallahassee', state='FL' WHERE id=95;
UPDATE crm_accounts SET address='619 S Woodward Ave', city='Tallahassee', state='FL' WHERE id=81;
UPDATE crm_accounts SET address='505 W Pensacola St', city='Tallahassee', state='FL' WHERE id=29;
UPDATE crm_accounts SET address='12062 WATERFRONT DRIVE', city='Tallahassee', state='FL' WHERE id=52;
UPDATE crm_accounts SET address='6500 Miccosukee Rd', city='Tallahassee', state='FL' WHERE id=5;
UPDATE crm_accounts SET address='107 Mississippi Ave', city='Panacea', state='FL' WHERE id=72;
UPDATE crm_accounts SET address='95 Riverside Dr', city='St Marks', state='FL' WHERE id=143;
UPDATE crm_accounts SET address='106 E Pine Ave', city='Eastpoint', state='FL' WHERE id=179;
UPDATE crm_accounts SET address='2810- Sharer Rd', city='Tallahassee', state='FL' WHERE id=149;
UPDATE crm_accounts SET address='3192 Coastal Hwy', city='Crawfordville', state='FL' WHERE id=42;
UPDATE crm_accounts SET address='10673 Florida Georgia Hwy', city='Havana', state='FL' WHERE id=161;
UPDATE crm_accounts SET address='471 JOHN KNOX RD', city='Tallahassee', state='FL' WHERE id=128;
UPDATE crm_accounts SET address='1350 E TENNESSEE STREET', city='Tallahassee', state='FL' WHERE id=89;
UPDATE crm_accounts SET address='1416 W Tennessee St', city='Tallahassee', state='FL' WHERE id=137;
UPDATE crm_accounts SET address='470 Suwannee St', city='Tallahassee', state='FL' WHERE id=51;
UPDATE crm_accounts SET address='1690 RAYMOND DIEHL ROAD', city='Tallahassee', state='FL' WHERE id=41;
UPDATE crm_accounts SET address='1950 Thomasville Road, STE G', city='Tallahassee', state='FL' WHERE id=50;
UPDATE crm_accounts SET address='705 S Woodward Ave', city='Tallahassee', state='FL' WHERE id=22;
UPDATE crm_accounts SET address='1500 BANNERMAN RD.', city='Tallahassee', state='FL' WHERE id=25;
UPDATE crm_accounts SET address='3425 THOMASVILLE RD.', city='Tallahassee', state='FL' WHERE id=4;
UPDATE crm_accounts SET address='6265 Old Water Oak Rd Suite 101-B', city='Tallahassee', state='FL' WHERE id=28;
UPDATE crm_accounts SET address='710 U.S. Hwy 27 South', city='Havana', state='FL' WHERE id=136;
UPDATE crm_accounts SET address='921 Thomasville Rd', city='Tallahassee', state='FL' WHERE id=82;
UPDATE crm_accounts SET address='1400-1 VILLAGE SQUARE BLVD', city='Tallahassee', state='FL' WHERE id=19;
UPDATE crm_accounts SET address='416 E TENNESSEE ST', city='Tallahassee', state='FL' WHERE id=79;
UPDATE crm_accounts SET address='1917 W. PENSACOLA ST.', city='Tallahassee', state='FL' WHERE id=69;
UPDATE crm_accounts SET address='8703 HAVANA HWY', city='Havana', state='FL' WHERE id=74;
UPDATE crm_accounts SET address='2814 APALACHEE PRKWY.', city='Tallahassee', state='FL' WHERE id=196;