UPDATE crm_accounts SET address='14073 EMERALD COAST PARKWAY', city='Destin', state='FL' WHERE id=497;
UPDATE crm_accounts SET address='100 Pier Park Dr', city='Panama City Beach', state='FL' WHERE id=408;
UPDATE crm_accounts SET address='405 Reid Ave', city='Port St Joe', state='FL' WHERE id=872;
UPDATE crm_accounts SET address='187 JOHN SIMS PKWY', city='Niceville', state='FL' WHERE id=817;
UPDATE crm_accounts SET address='995 US-98', city='Destin', state='FL' WHERE id=865;
UPDATE crm_accounts SET address='684 7TH ST', city='Chipley', state='FL' WHERE id=841;
UPDATE crm_accounts SET address='3715 AIRPORT DR', city='Panama City', state='FL' WHERE id=164;
UPDATE crm_accounts SET address='19873 STATE ROAD 20 W', city='Blountstown', state='FL' WHERE id=886;
UPDATE crm_accounts SET address='2236 E County Hwy 30A', city='Santa Rosa Beach', state='FL' WHERE id=799;
UPDATE crm_accounts SET address='302 Harbor Blvd', city='Destin', state='FL' WHERE id=802;
UPDATE crm_accounts SET address='15 AVENUE F', city='Apalachicola', state='FL' WHERE id=805;
UPDATE crm_accounts SET address='803 Main St', city='Chipley', state='FL' WHERE id=813;
UPDATE crm_accounts SET address='100 MARKET STREET', city='Apalachicola', state='FL' WHERE id=806;
UPDATE crm_accounts SET address='170 WALTER STREET', city='Apalachicola', state='FL' WHERE id=822;
UPDATE crm_accounts SET address='23028 PANAMA CITY BEACH PKWY', city='Panama City Beach', state='FL' WHERE id=828;
UPDATE crm_accounts SET address='8410 Front Beach Rd', city='Panama City Beach', state='FL' WHERE id=90;
UPDATE crm_accounts SET address='2216 FL-71', city='Marianna', state='FL' WHERE id=830;
UPDATE crm_accounts SET address='2080 W Hwy 98', city='Port St Joe', state='FL' WHERE id=832;
UPDATE crm_accounts SET address='545 E 6th St', city='Panama City', state='FL' WHERE id=130;
UPDATE crm_accounts SET address='425 Victory Blvd', city='Freeport', state='FL' WHERE id=807;
UPDATE crm_accounts SET address='1937 CR C30', city='Port St Joe', state='FL' WHERE id=811;
UPDATE crm_accounts SET address='34940 EMERALD COAST PKWY', city='Destin', state='FL' WHERE id=839;
UPDATE crm_accounts SET address='130 HWY 98', city='Apalachicola', state='FL' WHERE id=798;
UPDATE crm_accounts SET address='331 N BOB LITTLE ROAS', city='Callaway', state='FL' WHERE id=864;
UPDATE crm_accounts SET address='8166 HIGHWAY 90', city='Sneads', state='FL' WHERE id=1125;
UPDATE crm_accounts SET address='4975 Cape San Blas Rd', city='Port St Joe', state='FL' WHERE id=801;
UPDATE crm_accounts SET address='445 Harrison Ave', city='Panama City', state='FL' WHERE id=815;
UPDATE crm_accounts SET address='108 GOOD MORNING ST', city='Port St Joe', state='FL' WHERE id=844;
UPDATE crm_accounts SET address='4310 Cape San Blas Rd', city='Port St Joe', state='FL' WHERE id=804;
UPDATE crm_accounts SET address='625 15th St', city='Mexico Beach', state='FL' WHERE id=824;
UPDATE crm_accounts SET address='10343 E CO HWY 30A', city='Seacrest Beach', state='FL' WHERE id=849;
UPDATE crm_accounts SET address='1127 1/2 Beck Ave', city='Panama City', state='FL' WHERE id=848;
UPDATE crm_accounts SET address='411 CAPE SAN BLAS ROAD', city='PORT ST JOE', state='FL' WHERE id=821;
UPDATE crm_accounts SET address='4000 Marriott Dr', city='Panama City', state='FL' WHERE id=877;
UPDATE crm_accounts SET address='12 Via De Luna Dr', city='Pensacola Beach', state='FL' WHERE id=1150;
UPDATE crm_accounts SET address='5108 N 9th Ave', city='Pensacola', state='FL' WHERE id=520;
UPDATE crm_accounts SET address='6895-C N NINTH AVE N 9th Ave', city='Pensacola', state='FL' WHERE id=1154;
UPDATE crm_accounts SET address='23 Palafox Pl', city='Pensacola', state='FL' WHERE id=1145;
UPDATE crm_accounts SET address='312 E Government St', city='Pensacola', state='FL' WHERE id=1138;
UPDATE crm_accounts SET address='3808 N 12th Ave', city='Pensacola', state='FL' WHERE id=1038;
UPDATE crm_accounts SET address='6120 Enterprise Dr', city='Pensacola', state='FL' WHERE id=1171;
UPDATE crm_accounts SET address='6575 CAROLINE ST', city='Milton', state='FL' WHERE id=1135;
UPDATE crm_accounts SET address='196 Brooks St SE', city='Fort Walton Beach', state='FL' WHERE id=1129;
UPDATE crm_accounts SET address='1884 ANDORRA ST', city='Navarre', state='FL' WHERE id=1127;
UPDATE crm_accounts SET address='885 Scenic Hwy', city='Pensacola', state='FL' WHERE id=1139;
UPDATE crm_accounts SET address='1000 E 9 Mile Rd', city='Pensacola', state='FL' WHERE id=1136;
UPDATE crm_accounts SET address='6516 Caroline St', city='Milton', state='FL' WHERE id=1143;
UPDATE crm_accounts SET address='1660 Airport Blvd Unit 145', city='Pensacola', state='FL' WHERE id=1123;
UPDATE crm_accounts SET address='22-B VIA DELUNA DR', city='Pensacola Beach', state='FL' WHERE id=1160;
UPDATE crm_accounts SET address='130 E Government St', city='Pensacola', state='FL' WHERE id=1133;
