UPDATE crm_accounts SET address='6830 Suwannee Plaza Ln', city='Live Oak', state='FL' WHERE id=1175;
UPDATE crm_accounts SET address='563 FL-47', city='Lake City', state='FL' WHERE id=1177;
UPDATE crm_accounts SET address='313 NW Commons Loop', city='Lake City', state='FL' WHERE id=467;
UPDATE crm_accounts SET address='296 ROYAL PALMS DRIVE', city='Atlantic Beach', state='FL' WHERE id=1012;
UPDATE crm_accounts SET address='15 St George Street', city='Saint Augustine', state='FL' WHERE id=1003;
UPDATE crm_accounts SET address='1521 MARGARET ST', city='Jacksonville', state='FL' WHERE id=989;
UPDATE crm_accounts SET address='35 San Marco Ave', city='St. Augustine', state='FL' WHERE id=966;
UPDATE crm_accounts SET address='2461 3RD ST SOUTH', city='Jacksonville Beach', state='FL' WHERE id=993;
UPDATE crm_accounts SET address='1261 King St', city='Jacksonville', state='FL' WHERE id=260;
UPDATE crm_accounts SET address='24 CATHEDRAL PLACE', city='Saint Augustine', state='FL' WHERE id=1007;
UPDATE crm_accounts SET address='9825 San Jose Blvd', city='Jacksonville', state='FL' WHERE id=996;
UPDATE crm_accounts SET address='1011 ATLANTIC BLVD UNIT #6', city='Atlantic Beach', state='FL' WHERE id=1002;
UPDATE crm_accounts SET address='1975 SILVERLEAF PKWY', city='Saint Augustine', state='FL' WHERE id=492;
UPDATE crm_accounts SET address='474305 State Rd 200', city='Fernandina Beach', state='FL' WHERE id=1006;
UPDATE crm_accounts SET address='1 Anastasia Blvd', city='St. Augustine', state='FL' WHERE id=546;
UPDATE crm_accounts SET address='1605 County Road 220', city='Fleming Island', state='FL' WHERE id=1020;
UPDATE crm_accounts SET address='1037 Park St', city='Jacksonville', state='FL' WHERE id=420;
UPDATE crm_accounts SET address='450 State Road 13', city='Fruit Cove', state='FL' WHERE id=984;
UPDATE crm_accounts SET address='14376 Beach Blvd', city='Jacksonville', state='FL' WHERE id=949;
UPDATE crm_accounts SET address='929 Edgewood Ave S.', city='Jacksonville', state='FL' WHERE id=979;
UPDATE crm_accounts SET address='10601 San Jose Blvd', city='Jacksonville', state='FL' WHERE id=14;
UPDATE crm_accounts SET address='295 Pine Lakes Drive', city='Ponte Vedra', state='FL' WHERE id=970;
UPDATE crm_accounts SET address='1585 3RD STREET NORTH', city='Jacksonville Beach', state='FL' WHERE id=975;
UPDATE crm_accounts SET address='1124 NORTH 3RD ST', city='Jacksonville Beach', state='FL' WHERE id=987;
UPDATE crm_accounts SET address='13275 City Square Dr', city='Jacksonville', state='FL' WHERE id=998;
UPDATE crm_accounts SET address='6 Aviles St', city='St. Augustine', state='FL' WHERE id=968;
UPDATE crm_accounts SET address='61 San Marco Ave', city='St. Augustine', state='FL' WHERE id=971;
UPDATE crm_accounts SET address='1034 Edgewood Ave S', city='Jacksonville', state='FL' WHERE id=1013;
UPDATE crm_accounts SET address='119 E Bay St', city='Jacksonville', state='FL' WHERE id=826;
UPDATE crm_accounts SET address='1034 Park St', city='Jacksonville', state='FL' WHERE id=988;
UPDATE crm_accounts SET address='61 N LAURA STREET', city='Jacksonville', state='FL' WHERE id=999;
UPDATE crm_accounts SET address='4070 HERSCHEL STREET', city='Jacksonville', state='FL' WHERE id=781;
UPDATE crm_accounts SET address='245 Nocatee Center Way', city='Ponte Vedra Beach', state='FL' WHERE id=1000;
UPDATE crm_accounts SET address='12601 San Jose Blvd', city='Jacksonville', state='FL' WHERE id=554;
UPDATE crm_accounts SET address='715 RIVERSIDE AVENUE', city='JACKSONVILLE', state='FL' WHERE id=980;
UPDATE crm_accounts SET address='11112 San Jose Blvd', city='Jacksonville', state='FL' WHERE id=259;
UPDATE crm_accounts SET address='840 A1A N', city='Ponte Vedra Beach', state='FL' WHERE id=278;
UPDATE crm_accounts SET address='4413 Town Center Pkwy Ste 300', city='Jacksonville', state='FL' WHERE id=956;
UPDATE crm_accounts SET address='4180 3rd St S', city='Jacksonville Beach', state='FL' WHERE id=953;
UPDATE crm_accounts SET address='1302 Harrison Ave', city='Panama City', state='FL' WHERE id=876;
UPDATE crm_accounts SET address='1519 Tennessee Ave', city='Lynn Haven', state='FL' WHERE id=856;
UPDATE crm_accounts SET address='1125 Beck Ave', city='Panama City', state='FL' WHERE id=855;
UPDATE crm_accounts SET address='601 S PIER PARK DR', city='Panama City Beach', state='FL' WHERE id=1053;
UPDATE crm_accounts SET address='212 Monument Avenue', city='Port St Joe', state='FL' WHERE id=879;
UPDATE crm_accounts SET address='8501 Thomas Dr', city='Panama City Beach', state='FL' WHERE id=878;
UPDATE crm_accounts SET address='4368 W County Hwy 30A', city='Santa Rosa Beach', state='FL' WHERE id=838;
UPDATE crm_accounts SET address='11226 Hutchison Blvd', city='Panama City Beach', state='FL' WHERE id=453;
UPDATE crm_accounts SET address='27 BAY MAGNOLIA LANE', city='Santa Rosa Beach', state='FL' WHERE id=383;
UPDATE crm_accounts SET address='34 Goldenrod Cir', city='Santa Rosa Beach', state='FL' WHERE id=845;
UPDATE crm_accounts SET address='1127 1/2 Beck Ave', city='Panama City', state='FL' WHERE id=862;
UPDATE crm_accounts SET address='14073 EMERALD COAST PARKWAY', city='Destin', state='FL' WHERE id=497;
UPDATE crm_accounts SET address='100 Pier Park Dr', city='Panama City Beach', state='FL' WHERE id=408;
UPDATE crm_accounts SET address='405 Reid Ave', city='Port St Joe', state='FL' WHERE id=872;
UPDATE crm_accounts SET address='187 JOHN SIMS PKWY', city='Niceville', state='FL' WHERE id=817;
UPDATE crm_accounts SET address='995 US-98', city='Destin', state='FL' WHERE id=865;
UPDATE crm_accounts SET address='684 7TH ST', city='Chipley', state='FL' WHERE id=841;
UPDATE crm_accounts SET address='3715 AIRPORT DR', city='Panama City', state='FL' WHERE id=164;
UPDATE crm_accounts SET address='19873 STATE ROAD 20 W', city='Blountstown', state='FL' WHERE id=886;
UPDATE crm_accounts SET address='2236 E County Hwy 30A', city='Santa Rosa Beach', state='FL' WHERE id=799;
UPDATE crm_accounts SET address='302 Harbor Blvd', city='Destin', state='FL' WHERE id=802;
UPDATE crm_accounts SET address='15 AVENUE F', city='Apalachicola', state='FL' WHERE id=805;
UPDATE crm_accounts SET address='803 Main St', city='Chipley', state='FL' WHERE id=813;
UPDATE crm_accounts SET address='100 MARKET STREET', city='Apalachicola', state='FL' WHERE id=806;
UPDATE crm_accounts SET address='170 WALTER STREET', city='Apalachicola', state='FL' WHERE id=822;
UPDATE crm_accounts SET address='23028 PANAMA CITY BEACH PKWY', city='Panama City Beach', state='FL' WHERE id=828;
UPDATE crm_accounts SET address='8410 Front Beach Rd', city='Panama City Beach', state='FL' WHERE id=90;
UPDATE crm_accounts SET address='2216 FL-71', city='Marianna', state='FL' WHERE id=830;
UPDATE crm_accounts SET address='2080 W Hwy 98', city='Port St Joe', state='FL' WHERE id=832;
UPDATE crm_accounts SET address='545 E 6th St', city='Panama City', state='FL' WHERE id=130;
UPDATE crm_accounts SET address='425 Victory Blvd', city='Freeport', state='FL' WHERE id=807;
UPDATE crm_accounts SET address='1937 CR C30', city='Port St Joe', state='FL' WHERE id=811;
UPDATE crm_accounts SET address='34940 EMERALD COAST PKWY', city='Destin', state='FL' WHERE id=839;
UPDATE crm_accounts SET address='130 HWY 98', city='Apalachicola', state='FL' WHERE id=798;
UPDATE crm_accounts SET address='331 N BOB LITTLE ROAS', city='Callaway', state='FL' WHERE id=864;
UPDATE crm_accounts SET address='8166 HIGHWAY 90', city='Sneads', state='FL' WHERE id=1125;
UPDATE crm_accounts SET address='4975 Cape San Blas Rd', city='Port St Joe', state='FL' WHERE id=801;
UPDATE crm_accounts SET address='445 Harrison Ave', city='Panama City', state='FL' WHERE id=815;
UPDATE crm_accounts SET address='108 GOOD MORNING ST', city='Port St Joe', state='FL' WHERE id=844;
UPDATE crm_accounts SET address='4310 Cape San Blas Rd', city='Port St Joe', state='FL' WHERE id=804;
UPDATE crm_accounts SET address='625 15th St', city='Mexico Beach', state='FL' WHERE id=824;
UPDATE crm_accounts SET address='10343 E CO HWY 30A', city='Seacrest Beach', state='FL' WHERE id=849;
UPDATE crm_accounts SET address='1127 1/2 Beck Ave', city='Panama City', state='FL' WHERE id=848;
UPDATE crm_accounts SET address='411 CAPE SAN BLAS ROAD', city='PORT ST JOE', state='FL' WHERE id=821;
UPDATE crm_accounts SET address='4000 Marriott Dr', city='Panama City', state='FL' WHERE id=877;
UPDATE crm_accounts SET address='12 Via De Luna Dr', city='Pensacola Beach', state='FL' WHERE id=1150;
UPDATE crm_accounts SET address='5108 N 9th Ave', city='Pensacola', state='FL' WHERE id=520;
UPDATE crm_accounts SET address='6895-C N NINTH AVE N 9th Ave', city='Pensacola', state='FL' WHERE id=1154;
UPDATE crm_accounts SET address='23 Palafox Pl', city='Pensacola', state='FL' WHERE id=1145;
UPDATE crm_accounts SET address='312 E Government St', city='Pensacola', state='FL' WHERE id=1138;
UPDATE crm_accounts SET address='3808 N 12th Ave', city='Pensacola', state='FL' WHERE id=1038;
UPDATE crm_accounts SET address='6120 Enterprise Dr', city='Pensacola', state='FL' WHERE id=1171;
UPDATE crm_accounts SET address='6575 CAROLINE ST', city='Milton', state='FL' WHERE id=1135;
UPDATE crm_accounts SET address='196 Brooks St SE', city='Fort Walton Beach', state='FL' WHERE id=1129;
UPDATE crm_accounts SET address='1884 ANDORRA ST', city='Navarre', state='FL' WHERE id=1127;
UPDATE crm_accounts SET address='885 Scenic Hwy', city='Pensacola', state='FL' WHERE id=1139;
UPDATE crm_accounts SET address='1000 E 9 Mile Rd', city='Pensacola', state='FL' WHERE id=1136;
UPDATE crm_accounts SET address='6516 Caroline St', city='Milton', state='FL' WHERE id=1143;
UPDATE crm_accounts SET address='1660 Airport Blvd Unit 145', city='Pensacola', state='FL' WHERE id=1123;
UPDATE crm_accounts SET address='22-B VIA DELUNA DR', city='Pensacola Beach', state='FL' WHERE id=1160;
UPDATE crm_accounts SET address='130 E Government St', city='Pensacola', state='FL' WHERE id=1133;
UPDATE crm_accounts SET address='4949 Celebration Pointe Ave', city='Gainesville', state='FL' WHERE id=529;
UPDATE crm_accounts SET address='204 NE Hwy 441', city='Micanopy', state='FL' WHERE id=549;
UPDATE crm_accounts SET address='2019 E Silver Springs Blvd', city='Ocala', state='FL' WHERE id=683;
UPDATE crm_accounts SET address='2331 NW 13th St', city='Gainesville', state='FL' WHERE id=512;
UPDATE crm_accounts SET address='1201 SW 16TH AVE', city='Gainesville', state='FL' WHERE id=393;
UPDATE crm_accounts SET address='1017 WEST UNIVERSITY AVENUE', city='Gainesville', state='FL' WHERE id=919;
UPDATE crm_accounts SET address='3842 W Newberry Rd', city='Gainesville', state='FL' WHERE id=466;
UPDATE crm_accounts SET address='2751 W Torch Lake Dr', city='The Villages', state='FL' WHERE id=339;
UPDATE crm_accounts SET address='30 N Main St', city='Gainesville', state='FL' WHERE id=513;
UPDATE crm_accounts SET address='25335 WEST NEWBERRY RD', city='Newberry', state='FL' WHERE id=500;
UPDATE crm_accounts SET address='1545 NW 26th Ave', city='Chiefland', state='FL' WHERE id=503;
UPDATE crm_accounts SET address='11400 Turkey Creek Blvd', city='Alachua', state='FL' WHERE id=499;
UPDATE crm_accounts SET address='2 W Fort King St', city='Ocala', state='FL' WHERE id=1062;
UPDATE crm_accounts SET address='6111 SW 89 Ct Rd', city='Ocala', state='FL' WHERE id=485;
UPDATE crm_accounts SET address='5180 & 5186 SW 34TH STREET', city='Gainesville', state='FL' WHERE id=514;
UPDATE crm_accounts SET address='766 MARILEE PLACE', city='The Villages', state='FL' WHERE id=501;
UPDATE crm_accounts SET address='3445 W University Ave', city='Gainesville', state='FL' WHERE id=515;
UPDATE crm_accounts SET address='4860 NW 39TH AVENUE', city='Gainesville', state='FL' WHERE id=505;
UPDATE crm_accounts SET address='6998 US-27 Suite 112', city='Ocala', state='FL' WHERE id=480;
UPDATE crm_accounts SET address='2440 SW 76th St Suite 110', city='Gainesville', state='FL' WHERE id=484;
UPDATE crm_accounts SET address='48 S Magnolia Ave', city='Ocala', state='FL' WHERE id=507;
UPDATE crm_accounts SET address='103 SE 1st Ave', city='Ocala', state='FL' WHERE id=475;
UPDATE crm_accounts SET address='232 SE 1st St', city='Gainesville', state='FL' WHERE id=523;
UPDATE crm_accounts SET address='2405 W 27th Ave', city='Ocala', state='FL' WHERE id=491;
UPDATE crm_accounts SET address='1800 NE 23rd Ave', city='Gainesville', state='FL' WHERE id=528;
UPDATE crm_accounts SET address='1000 Old Mill Run', city='The Villages', state='FL' WHERE id=510;
UPDATE crm_accounts SET address='3965 Plaza Blvd Ste 10', city='Gainesville', state='FL' WHERE id=477;
UPDATE crm_accounts SET address='2000 Crawfordville Hwy STE G', city='Crawfordville', state='FL' WHERE id=187;
UPDATE crm_accounts SET address='2810 SHARER RD. UNIT#11', city='Tallahassee', state='FL' WHERE id=199;
UPDATE crm_accounts SET address='100 Tyron Cir', city='Tallahassee', state='FL' WHERE id=158;
UPDATE crm_accounts SET address='81001 S Gadsden St', city='Tallahassee', state='FL' WHERE id=105;
UPDATE crm_accounts SET address='3421 BANNERMAN RD', city='Tallahassee', state='FL' WHERE id=157;
UPDATE crm_accounts SET address='201 E Park Ave', city='Tallahassee', state='FL' WHERE id=102;
UPDATE crm_accounts SET address='3596 KINDHEGA DR.', city='Tallahassee', state='FL' WHERE id=145;
UPDATE crm_accounts SET address='620-1 Railroad Sq', city='Tallahassee', state='FL' WHERE id=162;
UPDATE crm_accounts SET address='1458 S MONROE STREET', city='Tallahassee', state='FL' WHERE id=241;
UPDATE crm_accounts SET address='1123 Thomasville Rd', city='Tallahassee', state='FL' WHERE id=250;
UPDATE crm_accounts SET address='805 S MACOMB ST', city='TALLAHASSEE', state='FL' WHERE id=214;
UPDATE crm_accounts SET address='600 W Gaines St', city='Tallahassee', state='FL' WHERE id=1121;
UPDATE crm_accounts SET address='3305 CAPITAL CIR NE', city='Tallahassee', state='FL' WHERE id=150;
UPDATE crm_accounts SET address='2910 Kerry Forest Pkwy', city='Tallahassee', state='FL' WHERE id=121;
UPDATE crm_accounts SET address='3491 Thomasville Rd', city='Tallahassee', state='FL' WHERE id=64;
UPDATE crm_accounts SET address='6668 Thomasville Rd', city='Tallahassee', state='FL' WHERE id=39;
UPDATE crm_accounts SET address='3551 BLAIRSTONE RD', city='Tallahassee', state='FL' WHERE id=62;
UPDATE crm_accounts SET address='2662 Fleischmann Rd', city='Tallahassee', state='FL' WHERE id=54;
UPDATE crm_accounts SET address='603 W Gaines St', city='Tallahassee', state='FL' WHERE id=119;
UPDATE crm_accounts SET address='1105 THARPE STREET', city='TALLAHASSEE', state='FL' WHERE id=210;
UPDATE crm_accounts SET address='202 S Adams St', city='Tallahassee', state='FL' WHERE id=154;
UPDATE crm_accounts SET address='2475 Apalachee Pkwy', city='Tallahassee', state='FL' WHERE id=125;
UPDATE crm_accounts SET address='513 W Gaines St', city='Tallahassee', state='FL' WHERE id=34;
UPDATE crm_accounts SET address='6800 THOMASVILLE RD.', city='TALLAHASSEE', state='FL' WHERE id=61;
UPDATE crm_accounts SET address='1650 N Monroe St', city='Tallahassee', state='FL' WHERE id=208;
UPDATE crm_accounts SET address='1950 Thomasville Rd', city='Tallahassee', state='FL' WHERE id=85;
UPDATE crm_accounts SET address='80 N Jefferson St', city='Monticello', state='FL' WHERE id=57;
UPDATE crm_accounts SET address='2020 W Pensacola St', city='Tallahassee', state='FL' WHERE id=245;
UPDATE crm_accounts SET address='3390 Capital Cir NE', city='Tallahassee', state='FL' WHERE id=49;
UPDATE crm_accounts SET address='151 LAUGHLING GULL LAND', city='Carrabelle', state='FL' WHERE id=129;
UPDATE crm_accounts SET address='320 E Tennessee St', city='Tallahassee', state='FL' WHERE id=104;
UPDATE crm_accounts SET address='3700 Golden Eagle Dr E', city='Tallahassee', state='FL' WHERE id=43;
UPDATE crm_accounts SET address='2738 Capital Cir NE', city='Tallahassee', state='FL' WHERE id=37;
UPDATE crm_accounts SET address='1026 N Monroe St', city='Tallahassee', state='FL' WHERE id=135;
UPDATE crm_accounts SET address='2837 Coastal Hwy', city='Crawfordville', state='FL' WHERE id=91;
UPDATE crm_accounts SET address='1954 Village Green Way', city='Tallahassee', state='FL' WHERE id=93;
UPDATE crm_accounts SET address='1304 N Monroe', city='Tallahassee', state='FL' WHERE id=110;
UPDATE crm_accounts SET address='6668-9 THOMASVILLE RD', city='Tallahassee', state='FL' WHERE id=246;
UPDATE crm_accounts SET address='306 1st St NW', city='Havana', state='FL' WHERE id=112;
UPDATE crm_accounts SET address='1307 N MONROE ST', city='Tallahassee', state='FL' WHERE id=165;
UPDATE crm_accounts SET address='4620 WOODVILLE HWY', city='Tallahassee', state='FL' WHERE id=147;
UPDATE crm_accounts SET address='3626 MAHAN DR.', city='Tallahassee', state='FL' WHERE id=160;
UPDATE crm_accounts SET address='3129 COOKS LANDING RD.', city='Quincy', state='FL' WHERE id=144;
UPDATE crm_accounts SET address='3862 Coastal Hwy', city='Crawfordville', state='FL' WHERE id=167;
UPDATE crm_accounts SET address='6653 THOMASVILLE RD', city='Tallahassee', state='FL' WHERE id=134;
UPDATE crm_accounts SET address='2700 Centerville Rd', city='Tallahassee', state='FL' WHERE id=183;
UPDATE crm_accounts SET address='1505 Jackson Bluff Rd', city='Tallahassee', state='FL' WHERE id=189;
UPDATE crm_accounts SET address='1840 N. MONROE STREET', city='TALLAHASSEE', state='FL' WHERE id=240;
UPDATE crm_accounts SET address='205 EAST PARK AVENUE SUITE#2', city='Tallahassee', state='FL' WHERE id=94;
UPDATE crm_accounts SET address='1481 Timberlane Rd', city='Tallahassee', state='FL' WHERE id=231;
UPDATE crm_accounts SET address='1242 S. JEFFERSON ST', city='Monticello', state='FL' WHERE id=226;
UPDATE crm_accounts SET address='200 COCA COLA AVE.', city='Havana', state='FL' WHERE id=216;
UPDATE crm_accounts SET address='445 SW COUNTRY CLUB RD', city='Madison', state='FL' WHERE id=232;
UPDATE crm_accounts SET address='325 N Bronough St', city='Tallahassee', state='FL' WHERE id=21;
UPDATE crm_accounts SET address='1011 S. MAGNOLIA', city='Tallahassee', state='FL' WHERE id=152;
UPDATE crm_accounts SET address='Hwy 98', city='Carrabelle', state='FL' WHERE id=83;
UPDATE crm_accounts SET address='14 Coastal Hwy', city='Panacea', state='FL' WHERE id=251;
UPDATE crm_accounts SET address='415 N Monroe St', city='Tallahassee', state='FL' WHERE id=46;
UPDATE crm_accounts SET address='7505 Preservation Rd', city='Tallahassee', state='FL' WHERE id=65;
UPDATE crm_accounts SET address='415 SAINT FRANCIS ST', city='Tallahassee', state='FL' WHERE id=109;
UPDATE crm_accounts SET address='1925 N MONROE ST', city='Tallahassee', state='FL' WHERE id=60;
UPDATE crm_accounts SET address='411 N MAGNOLIA DRIVE', city='Tallahassee', state='FL' WHERE id=239;
UPDATE crm_accounts SET address='3031 Crump rd', city='Tallahassee', state='FL' WHERE id=211;
UPDATE crm_accounts SET address='1018 Apalachee Pkwy', city='Tallahassee', state='FL' WHERE id=138;
UPDATE crm_accounts SET address='1318 N. MONROE SUITE B', city='Tallahassee', state='FL' WHERE id=163;
UPDATE crm_accounts SET address='1123 Thomasville Rd', city='Tallahassee', state='FL' WHERE id=200;
UPDATE crm_accounts SET address='8147 APALACHEE PARKWAY', city='Tallahassee', state='FL' WHERE id=139;
UPDATE crm_accounts SET address='1460 Market St', city='Tallahassee', state='FL' WHERE id=68;
UPDATE crm_accounts SET address='1327 S Monroe Unit 105', city='Tallahassee', state='FL' WHERE id=66;
UPDATE crm_accounts SET address='1123 THOMASVILLE RD', city='TALLAHASSEE', state='FL' WHERE id=141;
UPDATE crm_accounts SET address='101 W Pine Ave', city='St George Island', state='FL' WHERE id=126;
UPDATE crm_accounts SET address='400 Cedar Hill Rd', city='Tallahassee', state='FL' WHERE id=175;
UPDATE crm_accounts SET address='3813 N. MONROE ST', city='Tallahassee', state='FL' WHERE id=58;
UPDATE crm_accounts SET address='1216 - 4 NORTH MONROE STREET', city='Tallahassee', state='FL' WHERE id=159;
UPDATE crm_accounts SET address='504 All Saints St', city='Tallahassee', state='FL' WHERE id=197;
UPDATE crm_accounts SET address='850 PORT LEON DRIVE', city='St. Marks', state='FL' WHERE id=55;
UPDATE crm_accounts SET address='302 W 9TH AVE', city='Havana', state='FL' WHERE id=133;
UPDATE crm_accounts SET address='2111 NE CAPITAL CIRCLE', city='Tallahassee', state='FL' WHERE id=146;
UPDATE crm_accounts SET address='1235 APALACHEE PARKWAY', city='Tallahassee', state='FL' WHERE id=40;
UPDATE crm_accounts SET address='316 WEST TENNESSEE STREET', city='Tallahassee', state='FL' WHERE id=171;
UPDATE crm_accounts SET address='3870 COASTAL HWY', city='Crawfordville', state='FL' WHERE id=191;
UPDATE crm_accounts SET address='1105 E Lafayette St', city='Tallahassee', state='FL' WHERE id=594;
UPDATE crm_accounts SET address='228 FRANKLIN BLVD', city='St. George Island', state='FL' WHERE id=87;
UPDATE crm_accounts SET address='1600 Summit Lake Dr', city='Tallahassee', state='FL' WHERE id=209;
UPDATE crm_accounts SET address='10 N Adams St', city='Quincy', state='FL' WHERE id=173;
UPDATE crm_accounts SET address='123 East 5th Ave', city='Tallahassee', state='FL' WHERE id=108;
UPDATE crm_accounts SET address='2550 Pottsdamer St', city='Tallahassee', state='FL' WHERE id=156;
UPDATE crm_accounts SET address='101 S Adams St', city='Tallahassee', state='FL' WHERE id=107;
UPDATE crm_accounts SET address='2717 Mahan Dr', city='Tallahassee', state='FL' WHERE id=31;
UPDATE crm_accounts SET address='2911 THOMASVILLE ROAD', city='Tallahassee', state='FL' WHERE id=67;
UPDATE crm_accounts SET address='101 NORTH BLAIRSTONE RD', city='Tallahassee', state='FL' WHERE id=555;
UPDATE crm_accounts SET address='824 RAILROAD AVE', city='Tallahassee', state='FL' WHERE id=573;
UPDATE crm_accounts SET address='3431 BANNERMAN RD', city='Tallahassee', state='FL' WHERE id=166;
UPDATE crm_accounts SET address='1700-9 NORTH MONROE ST', city='Tallahassee', state='FL' WHERE id=176;
UPDATE crm_accounts SET address='6725 Mahan Dr', city='Tallahassee', state='FL' WHERE id=95;
UPDATE crm_accounts SET address='619 S Woodward Ave', city='Tallahassee', state='FL' WHERE id=81;
UPDATE crm_accounts SET address='505 W Pensacola St', city='Tallahassee', state='FL' WHERE id=29;
UPDATE crm_accounts SET address='12062 WATERFRONT DRIVE', city='Tallahassee', state='FL' WHERE id=52;
UPDATE crm_accounts SET address='6500 Miccosukee Rd', city='Tallahassee', state='FL' WHERE id=5;
UPDATE crm_accounts SET address='107 Mississippi Ave', city='Panacea', state='FL' WHERE id=72;
UPDATE crm_accounts SET address='95 Riverside Dr', city='St Marks', state='FL' WHERE id=143;
UPDATE crm_accounts SET address='106 E Pine Ave', city='Eastpoint', state='FL' WHERE id=179;
UPDATE crm_accounts SET address='2810- Sharer Rd', city='Tallahassee', state='FL' WHERE id=149;
UPDATE crm_accounts SET address='3192 Coastal Hwy', city='Crawfordville', state='FL' WHERE id=42;
UPDATE crm_accounts SET address='10673 Florida Georgia Hwy', city='Havana', state='FL' WHERE id=161;
UPDATE crm_accounts SET address='471 JOHN KNOX RD', city='Tallahassee', state='FL' WHERE id=128;
UPDATE crm_accounts SET address='1350 E TENNESSEE STREET', city='Tallahassee', state='FL' WHERE id=89;
UPDATE crm_accounts SET address='1416 W Tennessee St', city='Tallahassee', state='FL' WHERE id=137;
UPDATE crm_accounts SET address='470 Suwannee St', city='Tallahassee', state='FL' WHERE id=51;
UPDATE crm_accounts SET address='1690 RAYMOND DIEHL ROAD', city='Tallahassee', state='FL' WHERE id=41;
UPDATE crm_accounts SET address='1950 Thomasville Road, STE G', city='Tallahassee', state='FL' WHERE id=50;
UPDATE crm_accounts SET address='705 S Woodward Ave', city='Tallahassee', state='FL' WHERE id=22;
UPDATE crm_accounts SET address='1500 BANNERMAN RD.', city='Tallahassee', state='FL' WHERE id=25;
UPDATE crm_accounts SET address='3425 THOMASVILLE RD.', city='Tallahassee', state='FL' WHERE id=4;
UPDATE crm_accounts SET address='6265 Old Water Oak Rd Suite 101-B', city='Tallahassee', state='FL' WHERE id=28;
UPDATE crm_accounts SET address='710 U.S. Hwy 27 South', city='Havana', state='FL' WHERE id=136;
UPDATE crm_accounts SET address='921 Thomasville Rd', city='Tallahassee', state='FL' WHERE id=82;
UPDATE crm_accounts SET address='1400-1 VILLAGE SQUARE BLVD', city='Tallahassee', state='FL' WHERE id=19;
UPDATE crm_accounts SET address='416 E TENNESSEE ST', city='Tallahassee', state='FL' WHERE id=79;
UPDATE crm_accounts SET address='1917 W. PENSACOLA ST.', city='Tallahassee', state='FL' WHERE id=69;
UPDATE crm_accounts SET address='8703 HAVANA HWY', city='Havana', state='FL' WHERE id=74;
UPDATE crm_accounts SET address='2814 APALACHEE PRKWY.', city='Tallahassee', state='FL' WHERE id=196;